### ISSUE TITLE
Implement joinpath method to mimic pathlib behavior

### ISSUE THREAD

**Issue by furechan** [aws-samples/s3pathlib-project#5]
The current `S3Path` class does not have a `joinpath` method as found in the `pathlib` library.

It seems to have a similarly named method `join_path` but with different semantics.

Please add a `joinpath` method compatible with standard `pathlib` semantics. 

Beyond the spelling difference the current method seems to require `S3Path` arguments. The `joinpath` method should accept any string argument the same way that the `/` operator does. The `joinpath` method is useful not only because it accepts multiple string parts but also because it can be chained with other method calls.

Thank You.

**Comment by MacHu-GWU** [comment]
@furechan got it, I would like to add this feature in the next version.

**Comment by furechan** [comment]
Thanks!

**Comment by MacHu-GWU** [comment]
@furechan added in [1.0.12](https://pypi.org/project/s3pathlib/1.0.12/)
